//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugHound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachement
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int TicketId { get; set; }
        public string FileName { get; set; }
        public bool UpLoaded { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTimeOffset> DateAttached { get; set; }
        public string FileUNQName { get; set; }
    
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
    }
}
