//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BugHound.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Attachements = new HashSet<Attachement>();
            this.Comments = new HashSet<Comment>();
            this.Histories = new HashSet<History>();
            this.Notifications = new HashSet<Notification>();
        }
    
        public int Id { get; set; }
        public int EnteredById { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public int PriorityId { get; set; }
        public string Title { get; set; }
        public int TypeId { get; set; }
        public int StatusId { get; set; }
        public int ProjectId { get; set; }
        public int AssignedId { get; set; }
        public System.DateTimeOffset LastedUpdated { get; set; }
        public string Narration { get; set; }
        public bool Attachments { get; set; }
    
        public virtual ICollection<Attachement> Attachements { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Notification> Notifications { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
